sudo: required
services:
  - docker

before_install:
  - docker build -t olegkariuk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run olegkariuk/react-test npm test -- --coverage

after_success:
  - docker build -t olegkariuk/multi-client ./client
  - docker build -t olegkariuk/multi-nginx ./nginx
  - docker build -t olegkariuk/multi-server ./server
  - docker build -t olegkariuk/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push olegkariuk/multi-client
  - docker push olegkariuk/multi-nginx
  - docker push olegkariuk/multi-server
  - docker push olegkariuk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-635771086592
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
